version: '{build}'

image: Visual Studio 2019

environment:
  matrix:
  - CONFIGURATION: Debug
    WINFSP: source
  - CONFIGURATION: Release
    WINFSP: source

init:
#- ps: iex ((new-object net.webclient).DownloadString('https://raw.githubusercontent.com/appveyor/ci/master/scripts/enable-rdp.ps1'))

install:
- git submodule update --init --recursive
# install Meson & Ninja
- appveyor AddMessage "Install Meson & Ninja" -Category Information
- appveyor DownloadFile https://github.com/mesonbuild/meson/releases/download/0.52.0/meson-0.52.0-64.msi
- for %%f in ("meson-*.msi") do start /wait msiexec /i %%f /qn
# install WinFsp
- appveyor AddMessage "Install WinFsp" -Category Information
- if %WINFSP%==stable appveyor DownloadFile https://github.com/billziss-gh/winfsp/releases/download/v1.5B4/winfsp-1.5.19320.msi
- if %WINFSP%==stable appveyor DownloadFile https://github.com/billziss-gh/winfsp/releases/download/v1.5B4/winfsp-tests-1.5.19320.zip
- if %WINFSP%==source tools\build-winfsp.bat %CONFIGURATION%
- if %WINFSP%==source copy ext\winfsp\build\VStudio\build\%CONFIGURATION%\winfsp-*.msi .
- if %WINFSP%==source copy ext\winfsp\build\VStudio\build\%CONFIGURATION%\winfsp-tests-*.zip .
- for %%f in ("winfsp-*.msi") do start /wait msiexec /i %%f /qn INSTALLLEVEL=1000
- for %%f in ("winfsp-tests-*.zip") do powershell -command "Expand-Archive -Path %%f -DestinationPath 'C:\Program Files (x86)\WinFsp\bin'"
# enable test-signing and verifier and reboot
- appveyor AddMessage "Change boot configuration and reboot" -Category Information
- bcdedit /set testsigning on
- verifier /standard /driver winfuse-x64.sys || ver>nul
- if exist %SystemRoot%\memory.dmp del %SystemRoot%\memory.dmp
- ps: Restart-Computer -Force
- ps: Start-Sleep -s 60

build_script:
- appveyor AddMessage "Reboot complete" -Category Information
- tools\build.bat %CONFIGURATION%
- for %%f in ("build\VStudio\build\%CONFIGURATION%\winfuse-*-x64.msi") do start /wait msiexec /i %%f /qn INSTALLLEVEL=1000

test_script:
- sc create WinFuse type=kernel binPath=C:\projects\winfuse\build\VStudio\build\%CONFIGURATION%\winfuse-x64.sys
- reg add HKLM\Software\WinFsp\Fsext /v 00093118 /d "WinFuse" /f /reg:32
- tools\nmake-ext-test.bat
- tools\run-tests.bat %CONFIGURATION%
- tools\run-tests.bat %CONFIGURATION% sample
- if exist %SystemRoot%\memory.dmp exit 1

on_finish:
- if exist %SystemRoot%\memory.dmp (7z a memory.dmp.zip %SystemRoot%\memory.dmp && appveyor PushArtifact memory.dmp.zip)
- verifier /query
#- ps: $blockRdp = $true; iex ((new-object net.webclient).DownloadString('https://raw.githubusercontent.com/appveyor/ci/master/scripts/enable-rdp.ps1'))
